version: '3.1'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 3030:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
